# Generated by Django 5.2.6 on 2025-09-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=100)),
                ('accuracy', models.CharField(max_length=100)),
                ('pp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pokedex_id', models.CharField(max_length=100)),
                ('type1', models.CharField(max_length=100)),
                ('type2', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('evolution_chain', models.CharField(max_length=100)),
                ('abilities', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
