# Generated by Django 5.2.6 on 2025-09-13 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_moves_pokemon_delete_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='moves',
            name='Pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='app.pokemon'),
        ),
    ]
