# Generated by Django 5.2.6 on 2025-09-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_moves_pokemon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moves',
            old_name='Pokemon',
            new_name='pokemon',
        ),
    ]
