# Generated by Django 5.2.6 on 2025-09-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_pokemon_moves_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moves',
            name='accuracy',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='moves',
            name='category',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='moves',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='moves',
            name='power',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='moves',
            name='pp',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='moves',
            name='type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='abilities',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolution_chain',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='height',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='location',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokedex_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.CharField(max_length=500),
        ),
    ]
